# Get Business Partners from S/4 sandbox
GET http://localhost:4004/odata/v4/business-partner/BusinessPartners?$top=10&$select=BusinessPartner,BusinessPartnerFullName,BusinessPartnerType,LegalForm,NameCountry,Industry
Accept: application/json

###

# Get all Policy Applications (local mock data)
GET http://localhost:4004/odata/v4/insurance/PolicyApplications?$expand=policy
Accept: application/json
